### ISSUE TITLE
Create a flow manager napp

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kyco-core-napps#18]
This napp will have a basic CRUD (U is not necessary for now) for flow manager.

**Comment by diraol** [comment]
@beraldoleal, this napp should keep record of the flows? (History)

Diego Rabatone Oliveira

Em 3 de out de 2016 10:13 AM, "Beraldo Leal" <notifications@github.com>
escreveu:

This napp will have a basic CRUD (U is not necessary for now) for flow
manager.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kytos/kyco-core-napps/issues/18>, or mute the thread

**Comment by beraldoleal** [comment]
Not for now. For delete lets use the name attribute of a flow, with some kytos id. Something like: kytos-flow-0230. We can have some cache on controller to avoid query switches all the time.

**Comment by cemsbr** [comment]
I know @raphaelmcobe is working in this, so I updated the labels. If it is finished, please close it.

**Comment by beraldoleal** [comment]
Thanks @raphaelmcobe
