### ISSUE TITLE
Cannot import app's class

### ISSUE THREAD

**Issue by cemsbr** [kytos/kyco-core-napps#21]
For example:
- my_app/
  - main.py
  - myclass.py

Both ways do not work in main.py:
- `from .myclass import MyClass` (preferred)
- `from myclass import MyClass`

The (dangerous) workaroud is:

``` python
sys.path.insert(0, dirname(__file__))
from myclass import MyClass
sys.path.pop(0)
```

**Comment by diraol** [comment]
@cemsbr This is due to the fact that the napp is not a module (it does not have ``__init__.py``). Eventually we can change this behavior, I'm not sure what is the best solution here.
If you "class" is not that much big, then you can just move it inside the "main.py" file and use 'locally'.
@beraldoleal what do you think?

**Comment by beraldoleal** [comment]
@diraol @cemsbr Def we should allow napps developers to import other files. This MUST be refactored.

**Comment by cemsbr** [comment]
This is already implemented in kyco project.
